version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers-legacy
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install --working-dir=./server/
      - run:
          name: npm ci
          command: |
            if [ ! -d ./server/node_modules ]; then
              cd server/; npm ci
            fi
      - run: cd server/; npm run dev
      - run:
          name: php test
          command: php ./server/vendor/bin/phpunit --configuration=./server/phpunit.xml
