version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers-legacy
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./server/
      - save_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
          paths:
            - .server/vendor
      - run:
          name: npm ci
          command: |
            cd server/; npm ci
      - run: cd server/; npm run dev
      # - run: cd server/; composer dump-autoload
      - run:
          name: php test
          command: php ./server/vendor/bin/phpunit/ --configuration=./server/phpunit.xml
