version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers-legacy
      - image: cimg/mysql:8.0
    environment:
      - APP_ENV: testing
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true;
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./server/
      - save_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
          paths:
            - .server/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./server/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d ./server/node_modules ]; then
              cd server/; npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./server/package-lock.json" }}
          paths:
            - ./server/node_modules
      - run: cd server/; npm run dev
      - run:
          name: get ready for mysql
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
            sudo docker-php-ext-install pdo_mysql
            default-authentication-plugin=mysql_native_password
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: php test
          command: cd server/; vendor/bin/phpunit
